feat: Initialize mempool dumpster path + test
flashbots/rbuilder pull request #14
Opened 2024-07-03 13:12 UTC by ferranbt

## 📝 Summary

Builds on top of https://github.com/flashbots/rbuilder/pull/13. This PR moves the initialisation of the mempool dumpster to the mempool dumpster datasource itself. Before, it was on the fetch command. This also enables a unit test that was ignored before.

---

## ✅ I have completed the following steps:

* [x] Run `make lint`
* [x] Run `make test`
* [x] Added tests (if applicable)

2024-07-05 08:12 UTC, metachris commented
A mempool dumpster daily archive can be about 2GB: https://mempool-dumpster.flashbots.net/ethereum/mainnet/2024-07/index.html

Feels too large to download in the default tests.

2024-07-10 16:49 UTC, ZanCorDX requested changes

2024-07-10 16:49 UTC, ZanCorDX commented on crates/rbuilder/src/backtest/fetch/mod.rs
> +            mempool::MempoolDumpsterDatasource::new(mempool_datadir).unwrap(),
Don't unwrap, propagate error.

2024-07-15 15:43 UTC, ZanCorDX approved these changes

2024-07-15 15:51 UTC, merged