Make IPC Path optional
flashbots/rbuilder pull request #314
Opened 2024-12-21 12:25 UTC by 7suyash7

Make `el_node_ipc_path` optional in config.

## ✅ I have completed the following steps:

* [✅ ] Run `make lint`
* [✅ ] Run `make test`
* [ ] Added tests (if applicable)

2024-12-30 14:48 UTC, ZanCorDX commented
Cleanup can't be disabled. 
Maybe https://github.com/flashbots/rbuilder/issues/302 is not so easy. It would need to trigger the cleanup from somewhere else (main block building loop?).

2024-12-31 09:32 UTC, ferranbt commented
Hey @7suyash7. @ZanCorDX is correct. I missed the cleaning part. Opened a new issue to fix that https://github.com/flashbots/rbuilder/issues/318

2025-01-03 16:05 UTC, ferranbt commented
Hey @7suyash7. Can you rebase on top of the main branch? I merged #327 and now you should be unblocked to make IPC optional.

2025-01-04 06:28 UTC, 7suyash7 commented
Hi, @ferranbt I just rebased on top of main. Can you please go through the changes?

2025-01-04 18:48 UTC, ferranbt commented on crates/rbuilder/src/live_builder/order_input/txpool_fetcher.rs
> +        // Early return if no IPC path
I would prefer to handle this at `start_orderpool_jobs` and either run `subscribe_to_txpool_with_blobs` if IPC is set or do not do it otherwise.

2025-01-04 18:48 UTC, ferranbt requested changes
Thank you for the change :). Left a comment.

2025-01-04 21:19 UTC, ferranbt requested changes

2025-01-04 21:19 UTC, ferranbt commented on crates/rbuilder/src/live_builder/order_input/txpool_fetcher.rs
> +        let provider = match ProviderBuilder::new()
Is this change necessary?

2025-01-04 21:19 UTC, ferranbt commented on crates/rbuilder/src/live_builder/order_input/mod.rs
> +        tokio::spawn(async {}) // Empty task
Instead of this, can you have an array of async handles and append this one if IPC is enabled?
```
let handles = [clean_job, rpc_server]

if ipc_is_enabled {
   let txpool_fetcher = subscribe_to_txpool...
   handles.add(txpool_fetcher)
}
```

2025-01-05 06:15 UTC, 7suyash7 commented on crates/rbuilder/src/live_builder/order_input/txpool_fetcher.rs
> +        let provider = match ProviderBuilder::new()
No, I removed it.

2025-01-05 06:16 UTC, 7suyash7 commented on crates/rbuilder/src/live_builder/order_input/mod.rs
> +        tokio::spawn(async {}) // Empty task
Yes, can you please check the new commit

2025-01-06 09:05 UTC, ferranbt requested changes
One last comment and it should be ready to merge.

2025-01-06 09:05 UTC, ferranbt commented on crates/rbuilder/src/live_builder/order_input/txpool_fetcher.rs
> +            .on_ipc(IpcConnect::new(config.ipc_path.unwrap()))
Is this change still necessary? We can fail with `?` and do not need to cancel `global_cancel`.

2025-01-06 09:47 UTC, 7suyash7 commented on crates/rbuilder/src/live_builder/order_input/txpool_fetcher.rs
> +            .on_ipc(IpcConnect::new(config.ipc_path.unwrap()))
Hi, using `?` here would mean that we would have to change the return type of the tokio::spawn to a `Result` instead of `()`, I looked at other spawned tasks (clean_job, rpc_server) and they all handle errors internally, so I thought I should do the same...
Also, for `global_cancel` - if the user specified a path to the IPC and it failed to connect, is shutting down not appropriate?
I'm happy to make both changes, just asking some questions for clarity

2025-01-06 10:42 UTC, ferranbt commented on crates/rbuilder/src/live_builder/order_input/txpool_fetcher.rs
> +            .on_ipc(IpcConnect::new(config.ipc_path.unwrap()))
That happens because you put the ProviderBuilder inside the spawn task. In the original code the provider is created outside. Would reverting to that work?
Also, remove the `unwrap` from the config.ipc_path.

2025-01-06 14:18 UTC, 7suyash7 commented on crates/rbuilder/src/live_builder/order_input/txpool_fetcher.rs
> +            .on_ipc(IpcConnect::new(config.ipc_path.unwrap()))
Got it, can you please check the latest commit? Rust patterns are somewhat new and confusing to me, thanks for the guidance!

2025-01-06 15:02 UTC, ferranbt approved these changes

2025-01-06 15:44 UTC, merged