Distribution logic
flashbots/rbuilder pull request #67
Opened 2024-07-16 14:00 UTC by dvush

## 📝 Summary

This implements a redistribution logic for the builder. It adds redistribution logic as part of the backtest and adds a binary to calculate output csv files.

## 💡 Motivation and Context

Redistribution refers to a process of dividing block profits between contribution signers.

To do that we
* built block and calculate its backtest profit
* exclude some signer and calculate profit as if this signer never sent any bundles
* the difference between two values (second one should be lower) is contribution by the given signer
* profit is divided proportionally to the contribution

For transactions sent through the rpc endpoint we can't use signer and instead we use tx origin or address specified as address to receive mev share refunds.

---

## ✅ I have completed the following steps:

* [ ] Run `make lint`
* [ ] Run `make test`
* [ ] Added tests (if applicable)

2024-07-16 20:58 UTC, ZanCorDX commented on crates/rbuilder/src/backtest/redistribute/cli/csv_output.rs
> +    pub fn write_header(&mut self) -> io::Result<()> {
Can write_header() be called inside new() and make it private?

2024-07-16 21:02 UTC, ZanCorDX commented on crates/rbuilder/src/backtest/redistribute/cli/mod.rs
> +    match cli.command {
Can we avoid the copy/paste on Block vs Range?

2024-07-16 21:14 UTC, ZanCorDX commented
Mempool txs are brought from Duration::minutes(3) ago (MempoolDumpsterDatasource) but in live buiding spawn_clean_orderpool_job keeps only TIME_TO_KEEP_BUNDLE_CANCELLATIONS: Duration = Duration::from_secs(60); are we handling this?

2024-07-17 09:17 UTC, ferranbt commented
I understand that the refund logic needs to be open source for the TEE builder and that part of that refund logic takes advantage of the bench tooling of the Rbuilder, but, could we move this logic to some TEE-builder specific repository?

This logic is part of a product offering from Flashbots and I do not think it belongs into the OSS version of the rbuilder.

2024-07-17 13:55 UTC, ZanCorDX requested changes
Mentioned copy/paste and timing stuff.

2024-07-17 17:19 UTC, ryanschneider commented on crates/rbuilder/src/backtest/backtest_build_range.rs
> +    ingored_signers: Vec<Address>,
Typo: 
```suggestion
    ignored_signers: Vec<Address>,
```

2024-07-17 17:19 UTC, ryanschneider commented on crates/rbuilder/src/backtest/backtest_build_range.rs
> +                block.filter_out_ignored_signers(&ingored_signers);
```suggestion
                block.filter_out_ignored_signers(&ignored_signers);
```

2024-07-18 12:17 UTC, dvush commented
I found some issues here that needs to be addressed.

@ferranbt I think the core logic should be in this repo but maybe some wrapper can be in another. The motivation is to have this updated with the rest of the repo and ease of maintenance.

2024-07-18 14:06 UTC, ferranbt commented
> The motivation is to have this updated with the rest of the repo and ease of maintenance.

What is the maintenance burden? The bench framework?

2024-08-01 12:20 UTC, dvush commented
Diff is super wierd, its actually rebased. Closing and reopening

2024-08-01 12:20 UTC, closed without merging